import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import axios from "axios";
import dotenv from "dotenv";
dotenv.config();
const app=express(), PORT=Number(process.env.PORT)||3000; app.use(express.json({limit:"1mb"}));
interface Lead {id:string;name:string;address:string;phone:string;website:string;category:string;source:string;confidence:number;status:string;email?:string;whatsapp?:string;socials?:string[];evidence?:string[];enrichmentStatus?:string}
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function normalize(item:any,index:number):Lead {const p=item.properties||{},name=String(p.name||p.operator||"Local sem nome").trim(),address=[p.street,p.housenumber,p.city,p.state,p.country].filter(Boolean).join(", ")||"Endereço não informado",phone=String(p.phone||p.contact?.phone||"").trim(),website=String(p.website||p.contact?.website||"").trim(),category=String(p.osm_value||p.type||"empresa").trim(),fields=[name!=="Local sem nome",address!=="Endereço não informado",!!phone,!!website].filter(Boolean).length; return {id:`osm:${p.osm_type||"feature"}:${p.osm_id||index}`,name,address,phone,website,category,source:"OpenStreetMap / Photon",confidence:Math.round(45+fields*13.75),status:"Novo",evidence:[],socials:[]}}
function dedupe(ls:Lead[]){const s=new Set<string>();return ls.filter(l=>{const k=`${l.name.toLowerCase()}|${l.address.toLowerCase()}`;if(s.has(k))return false;s.add(k);return true})}
async function collect(query:string){const q=query.replace(/\b(padarias|clínicas|academias)\b/gi,m=>(({padarias:"padaria",clínicas:"clínica",academias:"academia"} as any)[m.toLowerCase()]||m)).replace(/\s+\b(em|no|na|do|da)\b\s+/gi," ").replace(/\s+/g," ").trim(); const r=await axios.get("https://photon.komoot.io/api/",{params:{q:q.slice(0,180),limit:20},headers:{"User-Agent":"OlhoDeDeus/2.1 public-osint"},timeout:12000});return dedupe((r.data?.features||[]).map(normalize))}
function root(url:string){try{const u=new URL(/^https?:\/\//i.test(url)?url:`https://${url}`);return u.origin+"/"}catch{return ""}}
function uniq(a:string[]){return [...new Set(a.filter(Boolean))]}
async function allowed(url:string){try{const u=new URL(url),r=await axios.get(u.origin+"/robots.txt",{timeout:5000,headers:{"User-Agent":"OlhoDeDeus/2.1 public-osint"}});const lines=String(r.data).split(/\r?\n/);let active=false;for(const line of lines){const [k,v]=line.split(":",2).map(x=>x.trim().toLowerCase());if(k==="user-agent")active=v==="*"||v.includes("olhodedeeus");if(active&&k==="disallow"&&v&&new URL(url).pathname.startsWith(v))return false}return true}catch{return true}}
async function enrich(l:Lead){const site=root(l.website); if(!site){return {...l,enrichmentStatus:"sem-site",status:l.phone?"Verificado":"Revisar",evidence:uniq(l.evidence||[])}}
 if(!(await allowed(site)))return {...l,enrichmentStatus:"bloqueado-robots",status:"Revisar",evidence:uniq([...(l.evidence||[]),"robots.txt: acesso não permitido"]) };
 try {const r=await axios.get(site,{timeout:9000,maxContentLength:1500000,headers:{"User-Agent":"OlhoDeDeus/2.1 (public contact discovery)"}}),html=String(r.data),text=html.replace(/<[^>]+>/g," ");
  const emails=uniq([...html.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)].map(x=>x[0].toLowerCase()).filter(x=>!x.endsWith(".png")&&!x.includes("example."))); const tels=uniq([...html.matchAll(/(?:tel:|whatsapp[^\"']*?phone=|(?:\+?\d[\d\s().-]{8,}\d))/gi)].map(x=>x[0].replace(/^tel:/i,"").replace(/.*phone=/i,"").trim()).filter(x=>x.length>=8)); const wa=uniq([...html.matchAll(/https?:\/\/(?:wa\.me|api\.whatsapp\.com)\/[^\"'\s<]+/gi)].map(x=>x[0])); const socials=uniq([...html.matchAll(/https?:\/\/(?:www\.)?(?:instagram|facebook|linkedin|twitter|x|youtube|tiktok)\.com\/[^\"'\s<]+/gi)].map(x=>x[0]));
  const evidence=[...(l.evidence||[]),site]; const phone=l.phone||tels[0]||""; const email=l.email||emails[0]||""; return {...l,phone,email,whatsapp:l.whatsapp||wa[0]||"",socials:uniq([...(l.socials||[]),...socials]),enrichmentStatus:"enriquecido",evidence,confidence:Math.min(98,l.confidence+(email?8:0)+(phone&&!l.phone?6:0)+(wa.length?5:0)+(socials.length?3:0)),status:(phone||email||wa.length)?"Verificado":"Revisar"};
 }catch(e){return {...l,enrichmentStatus:"fonte-inacessível",status:"Revisar",evidence:uniq([...(l.evidence||[]),site+" (não acessível)"])}}
}
async function pipeline(query:string,emit:(x:any)=>void){emit({stage:"coordenador",message:"Coordenador preparando a captura"});await wait(120);emit({stage:"coleta",message:"Buscando em fontes públicas"});let leads:Lead[]=[];try{leads=await collect(query)}catch(e){console.warn("public source unavailable")};emit({stage:"normalizacao",message:"Normalizando nomes e endereços",count:leads.length});leads=dedupe(leads);emit({stage:"enriquecimento",message:`Enriquecendo ${leads.length} leads por páginas públicas`,count:leads.length,found:0,enriched:0,verified:0});let found=0,enriched=0,verified=0;for(let i=0;i<leads.length;i++){leads[i]=await enrich(leads[i]);if(leads[i].email||leads[i].phone||leads[i].whatsapp||leads[i].socials?.length)found++;if(leads[i].enrichmentStatus==="enriquecido")enriched++;if(leads[i].status==="Verificado")verified++;emit({stage:"enriquecimento",message:`Lead ${i+1}/${leads.length}: ${leads[i].name}`,lead:i+1,total:leads.length,found,enriched,verified,lead:leads[i]})}emit({stage:"finalizando",message:"Organizando leads na tabela local",count:leads.length,found,enriched,verified});return leads.sort((a,b)=>b.confidence-a.confidence)}
app.get("/health",(_q,res)=>res.json({ok:true,service:"olho-de-deus",pipeline:"osint-publico",source:"photon-osm",enrichment:"public-web"}));
app.post("/api/capture",async(req,res)=>{const q=String(req.body?.query||"").trim();if(!q)return res.status(400).json({error:"Informe um nicho, empresa ou localidade."});try{const leads=await pipeline(q,()=>{});return res.json({query:q,count:leads.length,leads})}catch{return res.status(502).json({error:"Fontes públicas indisponíveis no momento."})}});
app.get("/api/capture/stream",async(req,res)=>{const q=String(req.query.query||"").trim();if(!q)return res.status(400).json({error:"Informe um nicho, empresa ou localidade."});res.setHeader("Content-Type","text/event-stream");res.setHeader("Cache-Control","no-cache");res.setHeader("Connection","keep-alive");const send=(x:any)=>res.write(`data: ${JSON.stringify(x)}\n\n`);try{const leads=await pipeline(q,x=>send({type:"progress",...x}));send({type:"complete",query:q,count:leads.length,leads})}catch{send({type:"error",message:"Fontes públicas indisponíveis; nenhum dado foi perdido."})}res.end()});
async function setup(){if(process.env.NODE_ENV!=="production"){const vite=await createViteServer({server:{middlewareMode:true},appType:"spa"});app.use(vite.middlewares)}else{const d=path.join(process.cwd(),"dist");app.use(express.static(d));app.get("*",(_q,r)=>r.sendFile(path.join(d,"index.html")))}app.listen(PORT,"0.0.0.0",()=>console.log(`Olho de Deus running on ${PORT}`))}setup();
