import React,{useState}from'react';
import{Bot,BrainCircuit,Search,Database,Plug,Radio,ShieldCheck,Wrench,UserRound,ChevronRight}from'lucide-react';
const nodes=[
{id:'chat',name:'Chat e voz',type:'Interface',status:'Em publicação',icon:UserRound,desc:'Recebe pedidos por texto ou voz, mostra resultados e pergunta quando faltam informações.'},
{id:'orchestrator',name:'Orquestrador',type:'Agente central',status:'Planejado',icon:BrainCircuit,desc:'Interpreta a intenção e escolhe quais agentes especializados podem ajudar. Não deve inventar resultados nem executar ações externas sem autorização.'},
{id:'osint',name:'Agente OSINT',type:'Pesquisa pública',status:'Backend existente',icon:Search,desc:'Coordena pesquisas em fontes públicas permitidas, reúne evidências e apresenta confiança e origem. O pipeline atual é limitado; não é ainda um swarm completo.'},
{id:'connectors',name:'Agente de conectores',type:'Contas autorizadas',status:'Planejado',icon:Plug,desc:'Gerencia o estado de conexões. Login e senha ficam no site da plataforma em aba separada; não são coletados pelo Olho de Deus.'},
{id:'memory',name:'Memória + CRM',type:'Persistência',status:'Planejado',icon:Database,desc:'Guarda conversas e dados de negócio em workspace isolado, com controles de acesso, consentimento e possibilidade de revisão.'},
{id:'radar',name:'Radar e agenda',type:'Acompanhamento',status:'Planejado',icon:Radio,desc:'Acompanha tarefas agendadas, respostas e alertas das fontes conectadas; avisa a pessoa em vez de agir escondido.'},
{id:'security',name:'Agente de cibersegurança',type:'Proteção',status:'Planejado',icon:ShieldCheck,desc:'Verifica dependências, configurações e eventos suspeitos; recomenda contenção. A segurança também depende de controles técnicos, revisão humana e atualizações.'},
{id:'maintenance',name:'Agente de manutenção',type:'Correção',status:'Planejado',icon:Wrench,desc:'Detecta erros, cria diagnóstico e propõe correções. Mudanças em produção passam por testes e aprovação; não se autoaltera sem controle.'},
];
export default function AgentArchitecture(){const[selected,setSelected]=useState(nodes[1]);return <section className="architecture-page"><div className="architecture-head"><div><span className="eyebrow"><BrainCircuit size={15}/> MAPA DO CÉREBRO</span><h1>Como o Olho de Deus funciona</h1><p>Toque em um bloco para ver o papel de cada agente e o que já está implementado.</p></div><span className="architecture-badge">Arquitetura viva</span></div><div className="org-chart"><button className={'org-node user '+(selected.id==='chat'?'chosen':'')} onClick={()=>setSelected(nodes[0])}><UserRound/><b>Usuário</b><small>texto e voz</small></button><span className="org-line vertical"/><button className={'org-node central '+(selected.id==='orchestrator'?'chosen':'')} onClick={()=>setSelected(nodes[1])}><BrainCircuit/><b>Olho de Deus</b><small>orquestrador central · planejado</small></button><span className="org-line vertical"/><div className="org-branches">{nodes.slice(2).map((n,i)=><button key={n.id} className={'org-node '+(selected.id===n.id?'chosen':'')} onClick={()=>setSelected(n)}><n.icon/><b>{n.name}</b><small>{n.type}</small><em className={n.status==='Backend existente'?'live-status':''}>{n.status}</em></button>)}</div></div><div className="org-detail"><div className="detail-icon"><selected.icon/></div><div><span>{selected.type}</span><h2>{selected.name}</h2><p>{selected.desc}</p></div><ChevronRight/></div><div className="architecture-note"><b>Importante</b><p>O organograma descreve o desenho e o estado atual do projeto; não significa que todos os agentes e integrações já estejam ativos. O serviço deve combinar agentes, código determinístico, proteção de dados e validação humana — nenhum agente garante segurança absoluta.</p></div></section>}
