import React, { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
interface Lead { id:string; name:string; address:string; phone:string; email:string; website:string; socials:string[]; contactName:string; responsibleName:string; category:string; source:string; evidence:string[]; enrichmentStatus:string; confidence:number; status:string; }
const stages=["coordenador","coleta","normalizacao","deduplicacao","verificacao","enriquecimento","score","finalizando"];
const stageLabel:Record<string,string>={coordenador:"Coordenando agentes",coleta:"Buscando fontes públicas",normalizacao:"Normalizando dados",deduplicacao:"Deduplicando registros",verificacao:"Verificando sinais",enriquecimento:"Enriquecendo contatos",score:"Calculando confiança",finalizando:"Finalizando organização"};
export default function LeadDashboard(){
 const [query,setQuery]=useState(""); const [leads,setLeads]=useState<Lead[]>(()=>{try{return JSON.parse(localStorage.getItem("olho-leads")||"[]")}catch{return[]}}); const [running,setRunning]=useState(false); const [stage,setStage]=useState(""); const [message,setMessage]=useState("Pronto para uma nova captura"); const [error,setError]=useState(""); const [sourceCount,setSourceCount]=useState(0); const [processed,setProcessed]=useState(0); const [found,setFound]=useState(0);
 useEffect(()=>localStorage.setItem("olho-leads",JSON.stringify(leads)),[leads]); const verified=useMemo(()=>leads.filter(l=>l.status==="Verificado").length,[leads]);
 const capture=()=>{const term=query.trim();if(!term||running){if(!term)setError("Digite um nicho ou localidade para iniciar.");return} setRunning(true);setError("");setLeads([]);setSourceCount(0);setProcessed(0);setFound(0);setStage("coordenador");setMessage("Coordenador preparando a captura"); const stream=new EventSource(`/api/capture/stream?query=${encodeURIComponent(term)}`); stream.onmessage=event=>{const d=JSON.parse(event.data);if(d.type==="progress"){setStage(d.stage);setMessage(d.message);if(d.count!==undefined)setSourceCount(d.count);if(d.processed!==undefined)setProcessed(d.processed);if(d.found!==undefined)setFound(d.found)}if(d.type==="complete"){setLeads(d.leads||[]);setSourceCount(d.count||0);setStage("finalizando");setMessage(`${d.count||0} leads organizados — ${ (d.leads||[]).filter((l:Lead)=>l.phone||l.email).length} com contato público`);setRunning(false);stream.close()}if(d.type==="error"){setError(d.message);setRunning(false);stream.close()}};stream.onerror=()=>{if(running){setError("Não foi possível concluir a captura. Tente novamente.");setRunning(false)}stream.close()}};
 return <main className="shell"><header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={21}/></div><div><strong>Olho de Deus</strong><span>inteligência pública para prospecção</span></div></div><div className="online"><span/> Sistema online</div></header><section className="hero"><div className="eyebrow"><Activity size={15}/> CAPTURA AUTÔNOMA</div><h1>Encontre oportunidades<br/><em>com um único comando.</em></h1><p>OSINT público responsável: Photon/OSM, DuckDuckGo HTML e sites públicos. Sem Google, login ou inferência de responsáveis.</p><div className="capture-box"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&capture()} placeholder="Ex.: clínicas odontológicas em Belo Horizonte" disabled={running}/><button onClick={capture} disabled={running}>{running?<span className="spinner"/>:<Search size={18}/>} {running?"Capturando...":"Capturar leads"}</button></div>{error&&<div className="error">{error}</div>}</section>
 {running&&<section className="progress-card"><div className="progress-head"><div><b>{message}</b><small>{processed?`Progresso por lead: ${processed}/${sourceCount} · ${found} com contato público` : "Os agentes estão trabalhando automaticamente"}</small></div><span className="spinner dark"/></div><div className="steps">{stages.map((s,i)=><div className={stages.indexOf(stage)>=i?"step active":"step"} key={s}><span>{stages.indexOf(stage)>i?"✓":i+1}</span>{stageLabel[s]}</div>)}</div></section>}
 <section className="stats"><div><Users/><b>{leads.length}</b><small>Leads na tabela</small></div><div><ShieldCheck/><b>{verified}</b><small>Com telefone/e-mail</small></div><div><CheckCircle2/><b>{sourceCount||leads.length}</b><small>Encontrados na fonte</small></div></section>
 <section className="table-card"><div className="table-head"><div><h2>Base de leads</h2><p>{leads.length?"Dados públicos com evidência de origem. Responsáveis só aparecem quando publicados explicitamente.":"Os resultados da próxima captura aparecerão aqui."}</p></div><span className="badge">{leads.length} registros</span></div><div className="table-wrap"><table><thead><tr><th>Empresa / local</th><th>Endereço</th><th>Contatos públicos</th><th>Responsável publicado</th><th>Confiança</th><th>Status</th></tr></thead><tbody>{leads.length?leads.map(l=><tr key={l.id}><td><strong>{l.name}</strong><small>{l.category} · {l.source}<br/>{l.website?<a href={l.website} target="_blank" rel="noreferrer">site encontrado</a>:"site não encontrado"}</small></td><td>{l.address}</td><td>{l.phone||"—"}<br/>{l.email||"—"}{l.socials?.length>0&&<small><br/>redes sociais públicas</small>}</td><td>{l.responsibleName||"Não publicado"}</td><td><div className="confidence"><i style={{width:`${l.confidence}%`}}/><span>{l.confidence}%</span></div></td><td><span className={l.status==="Verificado"?"status good":"status review"}>{l.enrichmentStatus||l.status}</span>{l.evidence?.[0]&&<small><a href={l.evidence[0]} target="_blank" rel="noreferrer">evidência</a></small>}</td></tr>):<tr><td colSpan={6} className="empty">Nenhum lead capturado ainda.</td></tr>}</tbody></table></div></section><footer>Fontes públicas acessadas com respeito a robots.txt, timeout e limite de requisições · Sem login · Sem dados inventados</footer></main>;
}